using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using AutoMapper;

using DietPlanner.DTO.Auth;
using DietPlanner.DTO.Person;
using DietPlanner.DTO.Response;
using DietPlanner.Server.BLL.ExtensionMethods;
using DietPlanner.Server.BLL.Helpers;
using DietPlanner.Server.BLL.Interfaces;
using DietPlanner.Server.ControllerBases;
using DietPlanner.Server.Entities.Concrete;
using DietPlanner.Server.Entities.Enums;
using DietPlanner.Server.Filters;
using DietPlanner.Shared.DesignPatterns.FluentFactory;
using DietPlanner.Shared.ExtensionMethods;
using DietPlanner.Shared.StringInfo;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
namespace DietPlanner.Server.Controllers
{
    [ApiController]
    [Route("api/[controller]/[action]")]
    [CustomAuthorize(RoleInfo.Admin)]
    public class AdminController : CustomControllerBase
    {
        private readonly IGenericQueryService<Dietician> genericDieticianService;
        private readonly IGenericCommandService<Dietician> genericDieticianCommandService;
        private readonly IPersonService personService;
        private readonly IRoleService roleService;
        private readonly IMessageService messageService;
        private readonly IMapper mapper;

        public AdminController(
            IGenericQueryService<Dietician> genericDieticianService,
            IGenericCommandService<Dietician> genericDieticianCommandService,
            IPersonService personService,
            IRoleService roleService,
            IMessageService messageService,
            IMapper mapper)
        {
            this.genericDieticianService = genericDieticianService;
            this.genericDieticianCommandService = genericDieticianCommandService;
            this.personService = personService;
            this.roleService = roleService;
            this.messageService = messageService;
            this.mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> GetAllDietician()
        {
            return Response<IEnumerable<UserDto>>
                  .Success(await genericDieticianService.GetAllAsync<UserDto>(), StatusCodes.Status200OK)
                  .CreateResponseInstance();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDietician(UserCreateDto dto)
        {
            UserDto found = await personService.GetPersonByIdentityNumber(PersonType.Dietician, dto.IdentityNumber);
            if (found.IsNotNull())
                return Response<UserDto>.Fail(
                           statusCode: StatusCodes.Status400BadRequest,
                           isShow: true,
                           path: "[POST] api/admin/createdietician",
                           errors: "Girilen kimlik no ile kayıtlı bir diyetisyen zaten mevcut"
                           )
                    .CreateResponseInstance();
            Role dieticianRole = await roleService.GetRoleByName(RoleInfo.Dietician);

            string autoGeneratedPassword = PasswordHelper.CreateRandomPassword();

            UserCreateDto createDto = FluentFactory<UserCreateDto>.Init(dto)
                .GiveAValue(x => x.RoleId, dieticianRole.Id)
                .GiveAValue(x => x.CreateUserId, Guid.Parse(Response.Headers["userId"].ToString()))
                .GiveAValue(x => x.Password, autoGeneratedPassword)
                .Use(obj => obj.Password = BCrypt.Net.BCrypt.HashPassword(dto.Password))
                .Take();

            Dietician dietician = await genericDieticianCommandService.AddAsync(createDto);
            await genericDieticianCommandService.Commit();
            UserDto returnModel = mapper.Map<UserDto>(dietician);
            await messageService.SendWelcomeAsync(new()
            {
                FirstName = returnModel.FirstName,
                LastName = returnModel.LastName,
                Password = autoGeneratedPassword,
                ToEmail = returnModel.Email
            });
            return Response<UserDto>
                .Success(returnModel, StatusCodes.Status201Created)
                .CreateResponseInstance();
        }
    }
}
